version: "3.9"

services:
  server:
    image: sujalsa/ide-server-image:latest
    environment:
      CLIENT_URL:"http://3.108.254.28:3100"
      SANDBOX_MODE: container
      FORCED_BASE_IMAGE: sujalsa/dev-base:latest
      ALLOWLIST_IMAGES: sujalsa/dev-base:latest
      DIGEST_REQUIRED: "false"
      FORCED_NETWORK_MODE: bridge
      READONLY_ROOT: "false"
      SANDBOX_MEMORY: 1g
      SANDBOX_CPUS: "1.0"
      SANDBOX_AUTOREMOVE: "true"
      RETAIN_CAP_DROP_ALL: "1"
      ALLOWED_EXTRA_CAPS: ""
      USE_HOST_WORKSPACE: "false"
      WORKSPACES_ROOT: /workspaces
      WORKSPACE_PATH: /workspace
      MAX_CONCURRENT_SESSIONS: 20
      MAX_SESSIONS_PER_USER: 3
      MAX_IDLE_MINUTES: 120
      CLEAN_INTERVAL_SECONDS: 60
      INPUT_MAX_TOKENS_PER_SEC: 8000
      INPUT_BURST_BYTES: 16000
      RESOURCE_KILL_MEM_PERCENT: "90"
      RESOURCE_KILL_CPU_PERCENT: "350"
      RESOURCE_KILL_SUSTAIN_MS: "20000"
      RESOURCE_KILL_GRACE_MS: "5000"
      RESOURCE_CHECK_INTERVAL_MS: "2000"
      DEBUG_SANDBOX: "0"
      SERVER_INSTANCE_SECRET: "${SERVER_INSTANCE_SECRET}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"

  client:
    image: sujalsa/ide-client-image:latest
    environment:
      - VITE_REACT_APP_SERVER_URL=http://3.108.254.28:8080/
    depends_on:
      - server
    ports:
      - "3100:3000" # Host:Container

  dev-base:
    image: sujalsa/dev-base:latest
    profiles: ["dont-start"] # Only for image build

volumes:
  server_workspaces:
