name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  SERVER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/ide-server-image
  CLIENT_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/ide-client-image
  DEVBASE_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/dev-base

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Build and push server image
      run: |
        docker build -t $SERVER_IMAGE:latest -f server/Dockerfile --target orchestrator ./server
        docker push $SERVER_IMAGE:latest

    - name: Build and push client image
      run: |
        docker build -t $CLIENT_IMAGE:latest -f client/Dockerfile ./client
        docker push $CLIENT_IMAGE:latest

    - name: Build and push dev-base image
      run: |
        docker build -t $DEVBASE_IMAGE:latest -f server/Dockerfile --target dev-base ./server
        docker push $DEVBASE_IMAGE:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd MY_CODE_SPACE
          git pull
          docker compose pull
          docker compose down
          docker compose up -d